version: "3"

services:
  seamark:
    # Replace this with image from registry
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:3001"
    environment:
      - AUDIT_URL=http://sheshbabu.com
      - DATABASE_URL=postgres://postgres:hunter2@db:5432/seamark
    command: npm start
    depends_on:
      - db

  db:
    image: postgres:11.3
    environment:
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_DB=seamark
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
